// ============================================================================
// Profile-photo storage — the file layer and the re-encode.
//
// THE ONE THING THIS FILE EXISTS TO GET RIGHT
// A photograph of a child is the most sensitive object this product stores, and
// there are exactly two ways to get it wrong:
//
//   1. Give it an address. A file under a directory a web server publishes is
//      readable by anyone who guesses or is told the name, forever, with no
//      authorization anywhere in the path. So nothing here is ever served
//      statically: the bytes live in UPLOADS_DIR, which Caddy has no route to,
//      and the only way out is GET /api/players/:id/photo (see routes.ts).
//      Names are 32 random hex characters — never the uploaded filename (which
//      is attacker-controlled and often carries the subject's own name), never
//      the user id (which is guessable from anything that lists users).
//
//   2. Strip the metadata in the browser. A JPEG straight off a phone carries
//      GPS coordinates, and stripping them client-side is theatre: anyone can
//      POST the original bytes to the endpoint directly and skip the browser
//      entirely. The only honest strip is the server-side re-encode below —
//      sharp decodes the pixels and writes a fresh WebP, carrying no metadata
//      across because nothing asks it to. The original bytes are never written
//      to disk; they exist only in the request's memory buffer.
//
// The format check is by MAGIC BYTES, not by the declared Content-Type (the
// client says it) and not by the file extension (also the client). A ".jpg"
// that is really a PDF is refused before sharp sees it.
// ============================================================================

import { randomBytes } from "node:crypto";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import { env } from "../env";

/** The formats a person's camera or phone actually produces. */
export const ACCEPTED_UPLOAD_MIMES = ["image/jpeg", "image/png", "image/webp"] as const;
export type AcceptedUploadMime = (typeof ACCEPTED_UPLOAD_MIMES)[number];

/**
 * Largest photo accepted, before re-encoding. 5 MB comfortably covers a modern
 * phone's full-resolution JPEG; anything larger is a camera raw or a mistake,
 * and either way there is no point spending memory on it to produce a 512-pixel
 * square.
 */
export const MAX_PHOTO_BYTES = 5 * 1024 * 1024;

/**
 * Slack allowed on top of MAX_PHOTO_BYTES when rejecting on `Content-Length`
 * alone. A multipart body is the file plus boundaries, headers and field names,
 * so a request carrying a legal 5 MB photo is a little over 5 MB. Without this
 * margin a 4.99 MB photo would be refused for being 5 MB of request.
 */
export const MULTIPART_OVERHEAD_BYTES = 64 * 1024;

/** Longest edge of the stored square. Enough for a retina 128-pixel avatar. */
export const PHOTO_MAX_EDGE = 512;

/** WebP quality. 82 is visually indistinguishable at avatar sizes. */
const PHOTO_WEBP_QUALITY = 82;

/** Every stored photo is a WebP today. Recorded on the row, not assumed. */
export const STORED_PHOTO_MIME = "image/webp";

/** Extension of the stored file. The id is the stem. */
const STORED_PHOTO_EXTENSION = ".webp";

/** A storage id is exactly this — checked again before any path is built. */
const PHOTO_ID_PATTERN = /^[0-9a-f]{32}$/;

// ── Where the files live ────────────────────────────────────────────────────

/**
 * Test seam, in the same spirit as `createHealthRouter(limit)`: the specs point
 * the store at a fresh temporary directory instead of the developer's real one.
 * Production never calls this, so `env.uploadsDir` remains the only answer the
 * running API can give.
 */
let dirOverride: string | undefined;

/** Point the store somewhere else. Pass `undefined` to restore the env value. */
export function setUploadsDirForTests(dir: string | undefined): void {
  dirOverride = dir;
}

/** The directory photos are written to and read from. */
export function uploadsDir(): string {
  return dirOverride ?? env.uploadsDir;
}

/**
 * Absolute path of one stored photo.
 *
 * The id is re-validated here rather than trusted from the caller. It is only
 * ever generated by `newPhotoId()` today, but it is also a value that has been
 * round-tripped through the database, and a path built from an unchecked string
 * is how `../../etc/passwd` gets read. The pattern admits no dot and no
 * separator, so there is nothing to traverse with.
 */
export function photoPath(photoId: string): string {
  if (!PHOTO_ID_PATTERN.test(photoId)) {
    throw new Error("Refusing to build a photo path from a malformed storage id");
  }
  return path.join(uploadsDir(), `${photoId}${STORED_PHOTO_EXTENSION}`);
}

/** A fresh, unguessable storage id: 128 bits as 32 hex characters. */
export function newPhotoId(): string {
  return randomBytes(16).toString("hex");
}

// ── The format check ────────────────────────────────────────────────────────

/**
 * The declared image format, read from the bytes themselves, or null when the
 * bytes are not one of the three formats accepted.
 *
 * Magic numbers, verified against sharp's own output:
 *   JPEG  ff d8 ff
 *   PNG   89 50 4e 47 0d 0a 1a 0a
 *   WebP  "RIFF" ...4-byte size... "WEBP"
 */
export function sniffImageMime(bytes: Buffer): AcceptedUploadMime | null {
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) {
    return "image/jpeg";
  }
  if (
    bytes.length >= 8 &&
    bytes[0] === 0x89 &&
    bytes[1] === 0x50 &&
    bytes[2] === 0x4e &&
    bytes[3] === 0x47 &&
    bytes[4] === 0x0d &&
    bytes[5] === 0x0a &&
    bytes[6] === 0x1a &&
    bytes[7] === 0x0a
  ) {
    return "image/png";
  }
  if (
    bytes.length >= 12 &&
    bytes.subarray(0, 4).toString("latin1") === "RIFF" &&
    bytes.subarray(8, 12).toString("latin1") === "WEBP"
  ) {
    return "image/webp";
  }
  return null;
}

// ── The re-encode (and therefore the metadata strip) ────────────────────────

/**
 * Decode, auto-orient, cover-crop to a square of at most 512×512, and re-encode
 * as WebP. The returned buffer carries no EXIF, no GPS, no XMP, no ICC and no
 * thumbnail — sharp only copies metadata when explicitly asked with
 * `withMetadata()`, and nothing here asks.
 *
 * `.rotate()` with no argument applies the EXIF orientation tag before the tag
 * is discarded. Without it, a portrait photo from a phone is stored on its side
 * — the orientation would be dropped along with everything else, and the pixels
 * were never rotated.
 *
 * Small images are not enlarged: the square's side is the smaller of 512 and the
 * image's own shorter edge, so a 200×300 upload is stored as a real 200×200
 * rather than a blurred 512×512.
 */
export async function reencodeToSquareWebp(bytes: Buffer): Promise<Buffer> {
  const probe = await sharp(bytes).metadata();
  const shorterEdge = Math.min(probe.width ?? PHOTO_MAX_EDGE, probe.height ?? PHOTO_MAX_EDGE);
  const side = Math.max(1, Math.min(PHOTO_MAX_EDGE, shorterEdge));

  return sharp(bytes)
    .rotate()
    .resize(side, side, { fit: "cover", position: "centre" })
    .webp({ quality: PHOTO_WEBP_QUALITY })
    .toBuffer();
}

// ── Reading and writing ─────────────────────────────────────────────────────

/**
 * Write the re-encoded bytes under `photoId`.
 *
 * Via a temporary name and a rename, which is atomic within a directory: a
 * process killed mid-write must not leave a half-file that the database row
 * already points at, because a truncated WebP is indistinguishable from a
 * corrupted one to everything downstream.
 */
export async function writePhoto(photoId: string, bytes: Buffer): Promise<void> {
  const target = photoPath(photoId);
  await mkdir(path.dirname(target), { recursive: true });
  const temporary = `${target}.tmp`;
  await writeFile(temporary, bytes);
  await rename(temporary, target);
}

/** The stored bytes, or null when the file is not there. */
export async function readPhoto(photoId: string): Promise<Buffer | null> {
  try {
    return await readFile(photoPath(photoId));
  } catch (err) {
    if (isMissingFile(err)) return null;
    throw err;
  }
}

/**
 * Delete a stored photo. Missing is success: the caller's goal is "these bytes
 * are gone", and a file that was already deleted satisfies it. Anything else
 * (a permission error, a read-only volume) is a real failure and propagates —
 * silently swallowing it is how an erased child's photo stays on disk.
 */
export async function deletePhoto(photoId: string | null | undefined): Promise<void> {
  if (!photoId) return;
  if (!PHOTO_ID_PATTERN.test(photoId)) return;
  await rm(photoPath(photoId), { force: true });
}

function isMissingFile(err: unknown): boolean {
  return typeof err === "object" && err !== null && (err as { code?: string }).code === "ENOENT";
}
