// Draft terms of service. Wired as a public route (/terms) from App.tsx.
//
// Same discipline as the privacy page: the counterparty, the address, the
// contact and the governing law are unresolved `<LegalToken>`s rather than
// invented specifics, and the effective date is a fixed constant instead of
// `new Date()`. See src/lib/legal/companyDetails.ts.
//
// One substantive correction from the previous draft: it said in-app guidance
// is "generated by rule-based logic". That is true of the session builder and
// false of match preparation, which goes to an external model whenever an
// operator configures one — so the warranty clause now separates the two.
import { Link } from "react-router-dom";
import { LegalDraftNotice } from "@/components/legal/LegalDraftNotice";
import { LegalToken } from "@/components/legal/LegalToken";
import { useT } from "@/lib/i18n";
import {
  COMPANY_ADDRESS,
  COMPANY_CONTACT_EMAIL,
  COMPANY_JURISDICTION,
  COMPANY_NAME,
  LEGAL_EFFECTIVE_DATE,
} from "@/lib/legal/companyDetails";

/** A heading + body block. The pages are almost entirely made of these. */
function Section({ heading, children }: { heading: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-lg font-bold text-foreground">{heading}</h2>
      <div className="mt-2 space-y-2">{children}</div>
    </section>
  );
}

/** One label/value row of the identity block. Every value is a token today. */
function DetailRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="grid grid-cols-1 gap-1 border-t border-border py-3 sm:grid-cols-[14rem_1fr] sm:gap-4">
      <dt className="text-foreground">{label}</dt>
      <dd>
        <LegalToken value={value} />
      </dd>
    </div>
  );
}

export default function TermsPage() {
  const { t } = useT();

  return (
    <div className="bg-background">
      <div className="container max-w-3xl py-16 md:py-20">
        <LegalDraftNotice />

        <h1 className="mt-10 text-3xl font-extrabold tracking-tight text-foreground">
          {t("legal.terms.title")}
        </h1>
        {/* A fixed constant, never `new Date()` — see companyDetails.ts. */}
        <p className="mt-2 flex flex-wrap items-center gap-2 text-sm text-muted-foreground">
          {t("legal.effectiveDate")}
          <LegalToken value={LEGAL_EFFECTIVE_DATE} />
        </p>

        <div className="mt-10 space-y-10 text-sm leading-relaxed text-muted-foreground">
          <Section heading={t("legal.terms.party.heading")}>
            <p>{t("legal.terms.party.note")}</p>
            <dl className="mt-4">
              <DetailRow label={t("legal.terms.party.providerLabel")} value={COMPANY_NAME} />
              <DetailRow label={t("legal.terms.party.addressLabel")} value={COMPANY_ADDRESS} />
              <DetailRow label={t("legal.terms.party.contactLabel")} value={COMPANY_CONTACT_EMAIL} />
            </dl>
          </Section>

          <Section heading={t("legal.terms.trial.heading")}>
            <p>{t("legal.terms.trial.body")}</p>
          </Section>

          {/* Stated rather than left as a gap. Silence where a price would go
              reads as "the billing terms must be somewhere else". There is no
              billing: nothing payment-related exists in the codebase at all. */}
          <Section heading={t("legal.terms.payments.heading")}>
            <p>{t("legal.terms.payments.body")}</p>
            <p>{t("legal.terms.payments.note")}</p>
          </Section>

          <Section heading={t("legal.terms.accounts.heading")}>
            <p>{t("legal.terms.accounts.body")}</p>
          </Section>

          <Section heading={t("legal.terms.minors.heading")}>
            <p>{t("legal.terms.minors.body")}</p>
          </Section>

          <Section heading={t("legal.terms.use.heading")}>
            <ul className="list-disc space-y-1.5 pl-5">
              <li>{t("legal.terms.use.item1")}</li>
              <li>{t("legal.terms.use.item2")}</li>
              <li>{t("legal.terms.use.item3")}</li>
              {/* item4 exists because item1 was not true of the product: an
                  opponent record is data about a third party who never
                  consented. The rule now names the exception and bounds it. */}
              <li>{t("legal.terms.use.item4")}</li>
            </ul>
          </Section>

          {/* Required now that a photograph can be uploaded — and kept
              proportionate. This is a profile picture, not a media platform,
              so the licence is the narrowest one that lets the feature work. */}
          <Section heading={t("legal.terms.content.heading")}>
            <p>{t("legal.terms.content.body")}</p>
            <p>{t("legal.terms.content.rights")}</p>
            <p>{t("legal.terms.content.licence")}</p>
            <p>{t("legal.terms.content.prohibited")}</p>
            <p>{t("legal.terms.content.removal")}</p>
          </Section>

          <Section heading={t("legal.terms.relationship.heading")}>
            <p>{t("legal.terms.relationship.body")}</p>
            <p>{t("legal.terms.relationship.noVetting")}</p>
            <p>{t("legal.terms.relationship.note")}</p>
          </Section>

          {/* The most important clause on the page. The product writes training
              sessions, recommends equipment and records injuries, and children
              use it — so what it is NOT has to be said in full, not implied by
              a line in the warranty clause. */}
          <Section heading={t("legal.terms.advice.heading")}>
            <p>{t("legal.terms.advice.body")}</p>
            <ul className="list-disc space-y-1.5 pl-5">
              <li>{t("legal.terms.advice.item1")}</li>
              <li>{t("legal.terms.advice.item2")}</li>
              <li>{t("legal.terms.advice.item3")}</li>
              <li>{t("legal.terms.advice.item4")}</li>
              <li>{t("legal.terms.advice.item5")}</li>
              <li>{t("legal.terms.advice.item6")}</li>
            </ul>
            <p className="font-medium text-foreground">{t("legal.terms.advice.health")}</p>
          </Section>

          <Section heading={t("legal.terms.data.heading")}>
            <p>
              {t("legal.terms.data.before")}{" "}
              <Link to="/privacy" className="text-primary hover:underline">
                {t("legal.privacy.linkLabel")}
              </Link>{" "}
              {t("legal.terms.data.after")}
            </p>
            <p>{t("legal.terms.data.erasure")}</p>
          </Section>

          {/* Matches the privacy page's erasure route on purpose. Two documents
              describing the same act differently is how a reader learns not to
              trust either. */}
          <Section heading={t("legal.terms.closure.heading")}>
            <p>{t("legal.terms.closure.body")}</p>
            <p>{t("legal.terms.closure.operator")}</p>
          </Section>

          <Section heading={t("legal.terms.warranty.heading")}>
            <p>{t("legal.terms.warranty.body")}</p>
            <p>{t("legal.terms.warranty.availability")}</p>
            <p>{t("legal.terms.warranty.note")}</p>
          </Section>

          <Section heading={t("legal.terms.changes.heading")}>
            <p>{t("legal.terms.changes.body")}</p>
          </Section>

          <Section heading={t("legal.terms.law.heading")}>
            <p>{t("legal.terms.law.note")}</p>
            <dl className="mt-4">
              <DetailRow label={t("legal.terms.law.lawLabel")} value={COMPANY_JURISDICTION} />
            </dl>
          </Section>

          <Section heading={t("legal.terms.contact.heading")}>
            <p>{t("legal.terms.contact.body")}</p>
          </Section>
        </div>

        <div className="mt-12 flex flex-wrap gap-x-6 gap-y-2 border-t border-border pt-6 text-sm">
          <Link to="/" className="font-medium text-primary hover:underline coarse:inline-flex coarse:min-h-11 coarse:items-center">
            {t("legal.backHome")}
          </Link>
          <Link to="/privacy" className="font-medium text-primary hover:underline coarse:inline-flex coarse:min-h-11 coarse:items-center">
            {t("legal.privacy.linkLabel")}
          </Link>
        </div>
      </div>
    </div>
  );
}
